### PR TITLE
Add showtimes booking urls

### PR DESCRIPTION
**Pull request by iuriaranda**
Google Movies also gives (when available) urls for each movie showtime, to buy tickets for that movie. So I've added a new property to the movie object with those urls: `showtime_tickets`

### CODE REVIEW

**Comment by erunion** [comment]
Awesome! You have an example zip code or theater where this is present?

**Comment by iuriaranda** [comment]
"Barcelona, Spain". There are various theaters here that have those links.

**Comment by erunion** [comment]
Can you run a lint check on this (`npm run lint`, though you might need to install [standard](https://www.npmjs.com/package/standard))? I'm Seeing a few things that are off from the coding standards the project has set up.

I'll merge this in after those are squared away.

**Comment by iuriaranda** [comment]
I've submitted the linting fixes. Hope that is ok now.

**Pull request merged**
