### PR TITLE
Getting theater by Id.

### LINKED ISSUE #2: .getTheater()
Need to be able to pass in a movie theater ID, like `1441318e8d47fc1b` for the [Vogue Theatre](http://google.com/movies?tid=1441318e8d47fc1b), in and get back an array of movies and showtimes for the configured day.

```javascript
var Showtimes = require('showtimes');
var s = new Showtimes(94118, {});
s.getTheater('1441318e8d47fc1b', function (movies) {
  /*[ { id: 'c30e28c6168184d9',
         name: 'Maleficent',
         runtime: '‎1hr 37min‎‎',
         rating: 'PG‎‎',
         genre: 'Action/Adventure‎',
         imdb: 'http://www.imdb.com/title/tt1587310/',
         trailer: 'http://www.youtube.com/watch?v=CelenfcEszk',
         showtimes: [ '‎2:45‎pm', '‎7:15pm‎'] },
       { id: 'd64ac30103cb0ea6',
         name: 'Maleficent 3D',
         runtime: '‎1hr 37min‎‎',
         rating: 'PG‎‎',
         genre: 'Action/Adventure‎',
         imdb: 'http://www.imdb.com/title/tt1587310/',
         trailer: 'http://www.youtube.com/watch?v=CelenfcEszk',
         showtimes: [ '‎5:00pm‎'] }]*/
});
```

### PR DESCRIPTION
**Pull request by chrux**
I want to resolve #2

### CODE REVIEW

**Comment by erunion** [comment]
Looks like there are merge conflicts with the query stuff you did; mind updating this branch so I can merge it in?

**Comment by chrux** [comment]
@erunion remember this is pending! I already fixed the conflicts.

**Comment by erunion** [comment]
@chrux Yeah, sorry, been busy with the day job. I'll play around with this tonight and get it merged.

**Comment by erunion** [comment]
Tagged to 2.1.0. Nice job.

**Pull request merged**
